Microtask1/urls.py
from django.conf.urls import url

from . import views

app_name='Microtask1'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^Microtask1/', views.main, name = 'main'),
    url(r'^Microtask2/', views.main2, name = 'main2'),
]

OutreachyWiki/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^', include('Microtask1.urls',namespace='Microtask1')),
    url(r'^admin/', admin.site.urls),
]

Microtask1/models.py
from django.db import models

# Create your models here.

Microtask1/views.py
from django.http import HttpResponse
from django.shortcuts import render
import math
import json
import requests
import toolforge

def index(request):
    return(render(request, 'Microtask1/home.html',{}))     

def main(request):
    if(request.method=='POST'):
        usr = request.POST['username']  #Here, we get the username fetched from html page
        URL = "https://en.wikipedia.org/w/api.php?action=query&format=json&list=usercontribs&ucuser="
        URL = URL + usr
        r = requests.get(URL)  #Recieved data in json-format
        if(r.status_code != 200):
            return(render(request,'Microtask1/index.html',{"error":'HTTP response ' + str(r.status_code)}))
        else:
            lst = json.loads(r.text)
            try:    
                if(lst['error']):
                    return(render(request,'Microtask1/index.html',{"error":lst['error']['info']}))
            except:   
                sub_lst = lst['query']['usercontribs'] #Contribution data extracted
                if(len(sub_lst)==0):
                    return(render(request,'Microtask1/index.html',{"error":"No Edits found"}))
            return(render(request,'Microtask1/index.html',{"contribution":sub_lst, "username":usr}))  #Here I send contribution for display on index.html page
    else:
        return(render(request,'Microtask1/index.html',{}))


def main2(request):
    if(request.method=='POST'):
        flag = 1
        usr = request.POST['username']
        SqlQuery1 = "SELECT user_editcount FROM user WHERE user_name='" + usr + "';"
        SqlQuery2 = "SELECT ss_total_edits FROM site_stats"
        #SqlQuery3 = "select rank from (select user_name, @curRank := @curRank + 1 as rank from user p, ( select @curRank := 0 ) q order by user_editcount DESC) q where user_name='"+usr+"';"
        SqlQuery3 = "SELECT 1+(SELECT count(*) from user a WHERE a.user_editcount > b.user_editcount) as RNK FROM user b WHERE user_name='"+usr+"';"
        SqlQuery4 = "select count(*) from user;"
        conn = toolforge.connect('kawiki_p')
        with conn.cursor() as curr:
            s1 = curr.execute(SqlQuery1)
            useredits_tup = curr.fetchall()
            s2 = curr.execute(SqlQuery2)
            totaledits_tup =curr.fetchall()
            s3 = curr.execute(SqlQuery3)
            userrank_tup = curr.fetchall()
            s4 = curr.execute(SqlQuery4)
            totalusers_tup = curr.fetchall()

        conn.close()
        try:    
            useredits = useredits_tup[0][0]
            totaledits = totaledits_tup[0][0]
            userrank = userrank_tup[0][0]
            totalusers = totalusers_tup[0][0]
        except:
            flag = 0 

        if(flag):    
            percentile = 100-((userrank*100)/(totalusers+1))
            rating = math.ceil((userrank/totalusers)*100)
            userrating = "User lies in top "+str(rating) + "%"
            return(render(request, 'Microtask1/task2.html',{'edits':useredits, 'name':usr, 'total_edits':totaledits, 'rank':userrank, 'total_users':totalusers, 'Percentile':percentile, 'user_rating':userrating}))
        
        return(render(request, 'Microtask1/task2.html',{"false_query":1}))
    else:
        return(render(request, 'Microtask1/task2.html',{}))

Microtask1/templates/Microtask1/home.html
<!DOCTYPE HTML>
<html>
<head>
	<title>Home Page</title>
</head>
<body>
	<center>
	<a href="{% url 'Microtask1:main' %}">Microtask1</a>  <br>
	<a href="{% url 'Microtask1:main2' %}">Microtask2</a> <br>
	</center>
</body>
</html>

Microtask1/templates/Microtask1/index.html
<!DOCTYPE html>
<html>
<head>
	<title> USER CONTRIBUTION SUMMARY </title>
</head>
<body>
		<center>
	     <form method="post"> 
	     	{% csrf_token %}
	     	Enter Username: <input type="text" name="username">
	     	<br>
	     	<br>
	     	<button type='submit'> Submit </button>
	     </form>
	    </center> 
	    
	    <h2>
	    {% if error %}
	    	{{error}}
	    {% endif %}
	    {% if username %}
	    	Username = {{username|safe}} <br>
	    	<!-- <a href="https://phabricator.wikimedia.org/p/{{username}}/"> Profile link </a> -->
		<br>
		<br>
		<h1>English Edits- </h1><br>
	    {% endif %}
		</h2>
	    {% for x in contribution %}  <!-- Here I traverse all the contributions and display the following div-->
	    <div>
	    	user = {{x.user}}
	    	Title = {{x.title}} <br>
	    	PageID = {{x.pageid}} <br>
	    	RevisionID = {{x.revid}} <br>
	    	ParentID = {{x.parentid}} <br>
	    	ns = {{x.ns}} <br>
	    	Timestamp = {{x.timestamp}} <br>
	    	Comment = {{x.comment}} <br>
	    	Size = {{x.size}} <br>

	    	<a href="https://en.wikipedia.org/w/index.php?title=User:{{x.user}}&amp;diff=prev&amp;oldid={{x.revid}}">
	    		click here to revise edit.
	    	</a>

	    	<br><br><br>

	    <div>
	    {% endfor %}
</body>
</html>

Microtask1/templates/Microtask1/task2.html
<!DOCTYPE html>
<html>
<head>
    <title>User Percentile</title>
</head>
<body>
        <center>
            <h2>Tool to display user Percentile and Rank in Georgian wiki</h2>
            <p>Enter initial letter of username in capital</p> <br>
            <form method="post">
                {% csrf_token %}
                Enter username: <input type="text" name="username">
                <br>
                <br>
                <button type='submit'> Submit </button>
                <a href="https://stats.wikimedia.org/EN/TablesWikipediaKA.htm">Click to see the list of users</a>
            </form>
        </center>
        <br>
        <br>
        <br>
        
        {% if false_query %}
            <h2>No user found</h2> <br>
        {% endif %}

        {% if name %}
            Name = {{name}} <br>
            Useredits = {{edits}} <br>
            Total_edits = {{total_edits}} <br>
            Rank = {{rank}} <br>
            Total_users = {{total_users}} <br>
            Percentile = {{Percentile}} <br>
            User rating = {{user_rating}} <br>
       {% endif %}

</body>
</html>